version: '3.5'

services:
  nebula.api:
    image: sitkacontainers.azurecr.io/nebula/api
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    ports:
      - "8121:80"
      - "8122:443"
