{{ if eq .Values.global.env.name "qa" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "web.fullname" . }}-qa-configmap
data:
  ASPNETCORE_ENVIRONMENT: "Staging"
  production: "false"
  staging: "true"
  dev: "false"
  mainAppApiUrl: "https://{{ .Values.global.domains.api }}"
  createAccountRedirectUrl: "https://{{ .Values.global.domains.web }}/create-user-callback"
  keystoneSupportBaseUrl: "https://identity.sitkatech.com/Authentication"
  geoserverMapServiceUrl: "https://{{ .Values.global.domains.geoserver }}/geoserver/Nebula"
  keystone_clientId: "Nebula"
  keystone_issuer: "https://identity-qa.sitkatech.com"
  keystone_redirectUriRelative: "/signin-oidc"
  keystone_scope: "openid profile offline_access keystone"
  keystone_sessionCheckEnabled: "false"
  keystone_logoutUrl: "https://identity-qa.sitkatech.com/account/logout"
  keystone_postLogoutRedirectUri: "/"
  keystone_waitForTokenInMsec: "500"
  keystone_responseType: "code"
  keystone_disablePKCE: "false"
  lyraBaseURL: "https://swn-lyra-dev.azurewebsites.net"
{{ end }}
