{{ if eq .Values.global.env.name "qa" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api.fullname" . }}-qa-configmap
data:
  SECRET_PATH: "/app/secrets/nebulaApiSecrets"
  DOCKER_BUILD_SOURCE: "."
  ASPNETCORE_ENVIRONMENT: "Staging"
  SITKA_EMAIL_REDIRECT: "notifications-qa@sitkatech.com"
  WEB_URL: "https://{{ .Values.global.domains.web }}"
  PlatformLongName: "UBBNRD Water Accounting Platform"
  LeadOrganizationLongName: "Upper Big Blue Natural Resources District"
  LeadOrganizationShortName: "UBB"
  LeadOrganizationHomeUrl: "https://www.upperbigblue.org/"
  LeadOrganizationEmail: ""
  APPINSIGHTS_INSTRUMENTATIONKEY: "{{ .Values.global.env.appInsightsInstrumentationKey }}"
  KEYSTONE_HOST: "https://identity-qa.sitkatech.com"
  KEYSTONE_REDIRECT_URL: "https://{{ .Values.global.domains.web }}/create-user-callback"
{{ end }}
