{{ if eq .Values.global.env.name "prod" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api.fullname" . }}-prod-configmap
data:
  SECRET_PATH: "/app/secrets/nebulaApiSecrets"
  DOCKER_BUILD_SOURCE: "."
  ASPNETCORE_ENVIRONMENT: "Production"
  SITKA_EMAIL_REDIRECT: ""
  WEB_URL: "https://{{ .Values.global.domains.web }}"
  LeadOrganizationEmail: ""
  APPINSIGHTS_INSTRUMENTATIONKEY: "{{ .Values.global.env.appInsightsInstrumentationKey }}"
  KEYSTONE_HOST: "https://identity.sitkatech.com"
  KEYSTONE_REDIRECT_URL: "https://{{ .Values.global.domains.web }}/create-user-callback"
{{ end }}